# Generated by Django 4.2.1 on 2025-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_husband_alter_women_tags_women_husband'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='marriage_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
